### ISSUE TITLE
Daddy channels add / request?

### ISSUE THREAD

**Issue by Hula1267** [dtankdempse/daddylive-m3u#8]
Can you add these one to all playlists? :)

Or could you tell us how I can add them manually to m3u-playlist-proxy? :)

#EXTINF:-1 tvg-id="RDSinfo.ca" tvg-name="RDS Info" tvg-logo="https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/rds-info-ca.png" group-title="SPORTS MISC (DADDY LIVE)" ,RDS Info
https://xyzdddd.mizhls.ru/lb/premium841/index.m3u8

#EXTINF:-1 tvg-id="RDS.ca" tvg-name="RDS" tvg-logo="https://raw.githubusercontent.com/tv-logo/tv-
https://xyzdddd.mizhls.ru/lb/premium839/index.m3u8

#EXTINF:-1 tvg-id="RDS2.ca" tvg-name="RDS2" tvg-logo="https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/rds-2-ca.png" group-title="SPORTS MISC (DADDY LIVE)" ,RDS 2
https://xyzdddd.mizhls.ru/lb/premium840/index.m3u8

#EXTINF:-1 tvg-id="TVASports.ca" tvg-name="TVA Sports" tvg-logo="https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/tva-sports-ca.png" group-title="SPORTS MISC (DADDY LIVE)" ,TVA Sports
https://xyzdddd.mizhls.ru/lb/premium833/index.m3u8

#EXTINF:-1 tvg-id="TVASports2.ca" tvg-name="TVA Sports 2" tvg-logo="https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/tva-sports-2-ca.png" group-title="SPORTS MISC (DADDY LIVE)" ,TVA Sports 2
https://xyzdddd.mizhls.ru/lb/premium834/index.m3u8

**Comment by dtankdempse** [comment]
I plan to add more channels when I have time, as mentioned [here](https://github.com/dtankdempse/daddylive-m3u/issues/3).

**Comment by Hula1267** [comment]
Hey sorry to reopen it, thanks for manual procedure. It works. :)) Any way to add EPG for the new channels?

**Comment by dtankdempse** [comment]
Since you're using your own playlist, consider importing it to [m3u4u.com](https://m3u4u.com/). This way, all channels I have assigned will already be linked to their EPG, and any new channels you add and assign will be included in your updated playlist. You can add EPG data to your channels, but the best way is to use the existing EPG provider: [m3u4u.com](https://m3u4u.com/).

Join their Discord for support: https://m3u4u.com/discord.

Currently, the EPG is down while the admin fixes some issues, but you shouldn't have trouble assigning channels.
